version: "3"

services:

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ../backend:/var/www/html
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    links:
      - php
    
  php:
    build: ./php
    volumes:
      - ../backend:/var/www/html/
      - ./keys:/var/www/keys/
    environment:
      - XDEBUG_CONFIG=remote_host=host.docker.internal
    links:
      - database

  node:
    image: node:latest
    working_dir: /webapp
    command: npm run serve
    volumes:
      - ../frontend:/webapp
    ports:
      - 8080:8080

  database:
    image: mysql:5.7
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=database
    volumes:
      - ./install/:/docker-entrypoint-initdb.d/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - database:db
    ports:
      - 81:80
    environment:
      - PMA_USER=root
      - PMA_PASSWORD=password
      - PHP_UPLOAD_MAX_FILESIZE=100MB
    